/* @imagine-readonly Generated by cloud schema sync. Do not edit manually. */

/**
 * Appwrite Configuration Constants
 *
 * This file contains configuration for the generated SDK.
 * You may modify these values as needed.
 */

export const PROJECT_ID = '69afff950029a71d0fd0'
export const ENDPOINT = 'https://cloud.appwrite.io/v1'

/**
 * API Key is required for server-side operations
 * Set the APPWRITE_API_KEY environment variable or replace this value directly.
 */
export const API_KEY = process.env.APPWRITE_API_KEY ?? ''
